apiVersion: v1
kind: PersistentVolume
metadata:
  name: chroma-data-pv
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/chroma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
