apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
      - name: chroma
        image: docker.io/chromadb/chroma:0.5.15
        ports:
        - containerPort: 8000
        env:
        - name: ALLOW_RESET
          value: "TRUE"
        volumeMounts:
        - name: chroma-data
          mountPath: /chromadb/data
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-data-pvc
